Changes to certain items
Merrokitsune/ronstation-EE pull request #3
Opened 2024-12-22 16:41 UTC by FlapstheMoth

### **STILL IN DEVELOPMENT**

# Description
Changes some fun things, ports reagents from the old ronstation github

# Changes
`Resources/Prototypes/Entities/Objects/Fun/crayons.yml`, crayons have been given more capacity

2024-12-22 17:50 UTC, Merrokitsune requested changes
Hey there. Thank you for your first PR, but I’ve got a couple more questions.

2024-12-22 18:14 UTC, FlapstheMoth commented
> Hey there. Thank you for your first PR, but I’ve got a couple more questions.

Yeah?

2024-12-23 22:53 UTC, FlapstheMoth commented
Haven't setup my localhost for EE, gonna do it later

2024-12-24 18:19 UTC, Merrokitsune requested changes
Thank you for requesting me to review.
So, I’ve got 3 things I noted:
1. Something (likely related to a key) is causing problems in nukeops.yml, resulting in a YAML linter fail:
![IMG_6095](https://github.com/user-attachments/assets/e165fb43-5a6f-428d-a750-666911b33f55)

2. I am not sure why did you delete a number of languages, but I think such removals are going to cause merge conflicts and other problems, since it’s upstream content.
![IMG_6096](https://github.com/user-attachments/assets/dcb03d86-fdba-420c-a31d-6cf0f86b5a22)

3. You still have not put your custom content, such as your reagents, your Vox language, and your syndicate cipher language, into their separate _Ronstation folders. If you wish to talk to me about this, let me know.

2024-12-24 18:19 UTC, Merrokitsune commented on Resources/Locale/en-US/language/languages.ftl
> +language-Gutter-name = Gutter
Renaming the language full-on can create difficulties, especially when upstream content is merged that has this language. You could, instead change the freespeak language name to “Gutter” instead.
```suggestion
language-Freespeak-name = Gutter
```

2024-12-24 18:19 UTC, Merrokitsune commented on Resources/Prototypes/Reagents/elements.yml
> +            Poison: 2
It would be wise to move all of our custom content to a “`_Ronstation`” (not “`Ronstation`”) folder, especially whatever custom reagents you add.

2024-12-24 18:19 UTC, Merrokitsune commented on Resources/Locale/en-US/language/languages.ftl
> +    evil gray come and go on my surface, as though light is being beamed from within.
@FlapstheMoth, this is not funny. Please revert.

2024-12-27 15:23 UTC, FlapstheMoth commented
Ready for review

2024-12-27 18:21 UTC, Merrokitsune requested changes
Hey there, apologies for the intense delay and stuff, but I noticed that there is a duplicate ID in the normal path:
![IMG_6117](https://github.com/user-attachments/assets/5ce14c05-f76b-4283-b797-13984dfdbb52)
There is evidence of this:
![IMG_6118](https://github.com/user-attachments/assets/f36b7708-4248-4af4-a37b-f218d18e76c5)
You might want to remove the chemical-containers.yml in the normal path (not the _Ronstation path).

2024-12-28 14:09 UTC, Merrokitsune requested changes
Hello.
![Screenshot from 2024-12-28 20-47-49](https://github.com/user-attachments/assets/efa43a14-0615-4fc6-aa5f-523cd4041253)
I noted there is still the Vox.yml in the proper path. You should remove that.
![Screenshot from 2024-12-28 20-49-42](https://github.com/user-attachments/assets/6f893d57-5c57-4b4b-b449-f7468607385e)
The Vox.yml in the proper path should be removed while the Vox.yml in the _Ronstation folder should be kept.
When that's done, and there's no errors, you can make the choice on wether to rearrange those language locales in languages.ftl or ping me for a merge.
Hope that helps. :)

2024-12-28 14:09 UTC, Merrokitsune commented on Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
> +  id: JugBromine
This should be removed entirely.

2024-12-28 19:29 UTC, merged